//
// Created by olliekrk on 01.11.2019.
//

#ifndef EMBEDDED_PLAYER_GUI_COLORS_H
#define EMBEDDED_PLAYER_GUI_COLORS_H

// sound buttons
#define COLOR_PRIMARY_DEFAULT LCD_COLOR_GRAY
#define COLOR_PRIMARY_DEFAULT_DARK LCD_COLOR_DARKGRAY
#define COLOR_ACCENT_DEFAULT LCD_COLOR_BLACK

// track buttons
#define COLOR_PRIMARY_OPTION LCD_COLOR_YELLOW
#define COLOR_ACCENT_OPTION LCD_COLOR_DARKYELLOW

// selected track panel
#define COLOR_PRIMARY_SELECTED LCD_COLOR_ORANGE
#define COLOR_ACCENT_SELECTED LCD_COLOR_LIGHTYELLOW

// directory buttons
#define COLOR_SECONDARY_OPTION LCD_COLOR_BROWN

// highlight
#define COLOR_HIGHLIGHTED LCD_COLOR_CYAN

// text
#define COLOR_TEXT LCD_COLOR_BLACK

#endif //EMBEDDED_PLAYER_GUI_COLORS_H
