//
// Created by olliekrk on 01.11.2019.
//

#ifndef EMBEDDED_PLAYER_GUI_COLORS_H
#define EMBEDDED_PLAYER_GUI_COLORS_H

#include <stm32746g_discovery_lcd.h>

#define COLOR_DEFAULT LCD_COLOR_LIGHTGRAY

#define COLOR_PRIMARY_DEFAULT LCD_COLOR_DARKGRAY
#define COLOR_ACCENT_DEFAULT LCD_COLOR_BLACK

#define COLOR_PRIMARY_OPTION LCD_COLOR_RED
#define COLOR_ACCENT_OPTION LCD_COLOR_LIGHTRED

#define COLOR_PRIMARY_SELECTED LCD_COLOR_DARKBLUE
#define COLOR_ACCENT_SELECTED LCD_COLOR_BLUE

#define COLOR_HIGHLIGHTED LCD_COLOR_CYAN

#endif //EMBEDDED_PLAYER_GUI_COLORS_H
